mongo_username = "username"
mongo_password = "password"
mongo_cluster_name = "cluster_name"
mongo_cluster_link = "cluster_link"
mongo_client_name = "new_client_name"
mongo_collection_name = "new_collection_name"
